# Generated by Django 6.0.5 on 2026-05-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('problem', models.CharField(choices=[('Login Issue', 'Login Issue'), ('Membership Problem', 'Membership Problem'), ('Payment Issue', 'Payment Issue'), ('Website Bug', 'Website Bug'), ('Trainer Complaint', 'Trainer Complaint'), ('Other', 'Other')], max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
