# Generated by Django 6.0.5 on 2026-05-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_con'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('trainer', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
