# Generated by Django 6.0.5 on 2026-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trainerform'),
    ]

    operations = [
        migrations.CreateModel(
            name='joined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=54)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
                ('plan', models.CharField(max_length=30)),
                ('trainer', models.CharField(max_length=30)),
                ('goal', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
